### PR TITLE
Switch to use new group coordinator API

### PR DESCRIPTION
**Pull request by tfoote**
This api has changed inside soco. Tested against soco 0.11.1

### CODE REVIEW

**Comment by RJ** [comment]
neat, would you update the readme too, to indicate the minimum version of soco supported with this change? then happy to merge

**Comment by tfoote** [comment]
I've added an update to the readme

**Comment by tfoote** [comment]
I added the current version. I think it would be comatible back to 0.8 which is where I see the .group alias working but the evolving API is not clear from the release notes.

**Comment by RJ** [comment]
thanks!

**Pull request merged**
